# Generated by Django 4.2.17 on 2025-01-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_is_paid_remove_order_payment_on_get'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='requires_delivery',
        ),
    ]
